//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INDAABIN.DI.CONTRATOS.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraSistema
    {
        public int IdBitacora { get; set; }
        public string BitacoraTabla { get; set; }
        public string BitacoraIdReg { get; set; }
        public string BitacoraCampo { get; set; }
        public string BitacoraValorAnt { get; set; }
        public string BitacoraObservaciones { get; set; }
        public int Fk_IdUsuarioRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    }
}
