//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INDAABIN.DI.CONTRATOS.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraExcepcion
    {
        public int IdBitacoraExepcion { get; set; }
        public string Aplicacion { get; set; }
        public string Modulo { get; set; }
        public string Funcion { get; set; }
        public string DescExcepcion { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string UsuarioRegistro { get; set; }
    }
}
