//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INDAABIN.DI.CONTRATOS.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_InstitucionContratosHistorico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cat_InstitucionContratosHistorico()
        {
            this.ContratoArrto_Historico = new HashSet<ContratoArrto_Historico>();
        }
    
        public int ClaveInstitucion { get; set; }
        public string NombreInstitucion { get; set; }
        public string DescripcionInstitucionDBCAT { get; set; }
        public Nullable<int> IdInstitucionDBCAT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoArrto_Historico> ContratoArrto_Historico { get; set; }
    }
}
