//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INDAABIN.DI.CONTRATOS.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmisionOpinonContrato
    {
        public int IdEmisionOpinionContrato { get; set; }
        public int Fk_IdAplicacionConcepto { get; set; }
        public int NumContrato { get; set; }
        public bool EsHistorico { get; set; }
        public bool EstatusRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int Fk_IdUsuarioRegistro { get; set; }
    
        public virtual AplicacionConcepto AplicacionConcepto { get; set; }
    }
}
