//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INDAABIN.DI.CONTRATOS.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcepcionNormativaContratoArrto
    {
        public int IdContratoArrto { get; set; }
        public byte IdTipoExcepcionNormativaContrato { get; set; }
        public string Observaciones { get; set; }
        public bool EstatusRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual Cat_TipoExcepcionNormativaContrato Cat_TipoExcepcionNormativaContrato { get; set; }
        public virtual ContratoArrto ContratoArrto { get; set; }
    }
}
