//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INDAABIN.DI.CONTRATOS.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class JustipreciacionArrto
    {
        public int IdJustipreciacion { get; set; }
        public Nullable<int> Fk_IdContratoArrto { get; set; }
        public string Secuencial { get; set; }
        public string SuperficieDictaminada { get; set; }
        public Nullable<System.DateTime> FechaDictamen { get; set; }
        public decimal MontoDictaminado { get; set; }
        public string EstatusAtencion { get; set; }
        public string NoGenerico { get; set; }
        public string UnidadMedidaSupRentableDictaminada { get; set; }
        public bool EstatusRegistro { get; set; }
        public int Fk_IdUsuarioRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual ContratoArrto ContratoArrto { get; set; }
    }
}
