//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INDAABIN.DI.CONTRATOS.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlazasInmueble
    {
        public int IdPlazaInm { get; set; }
        public string RFI { get; set; }
        public int Ramo { get; set; }
        public string UR { get; set; }
        public Nullable<int> NumPlazas { get; set; }
        public Nullable<bool> Operacion { get; set; }
        public int TotalPlazas { get; set; }
        public decimal SupConstM2 { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
        public bool Existe { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<int> EstatusRegistro { get; set; }
    }
}
