//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INDAABIN.DI.CONTRATOS.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepRFI_RIUF
    {
        public string RFI { get; set; }
        public Nullable<int> IdInstitucion { get; set; }
        public string Institucion { get; set; }
        public Nullable<int> IdPais { get; set; }
        public string Pais { get; set; }
        public Nullable<int> IdEntFederativa { get; set; }
        public string Estado { get; set; }
        public Nullable<int> IdMunicipio { get; set; }
        public string Municipio { get; set; }
        public string NombreAsentamiento { get; set; }
        public string NombreVialidad { get; set; }
        public string NumExterior { get; set; }
        public string NumInterior { get; set; }
        public string Nombre { get; set; }
        public string CodigoPostal { get; set; }
        public string CURT { get; set; }
        public Nullable<byte> PorcAccesibilidad { get; set; }
        public int TipoRep { get; set; }
        public System.DateTime FechaFinRep { get; set; }
    }
}
