//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INDAABIN.DI.CONTRATOS.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraductorRUSP_INST
    {
        public Nullable<double> CveInst { get; set; }
        public string NombreInst { get; set; }
        public Nullable<double> CveSector { get; set; }
        public string NomSector { get; set; }
        public Nullable<double> CveNatJuridica { get; set; }
        public string NatJuridica { get; set; }
        public Nullable<bool> flag { get; set; }
        public bool estatus { get; set; }
        public Nullable<double> Ramo { get; set; }
        public string UR { get; set; }
        public string UnidadResponsableSHCP { get; set; }
    }
}
