//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INDAABIN.DI.CONTRATOS.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRADUCTOR_cat
    {
        public int Fk_IdInstitucion { get; set; }
        public string nombreInstitucionOrg { get; set; }
        public string nombreInstitucion { get; set; }
        public int Fk_IdInstitucionDB { get; set; }
        public string nombreInstitucionDB { get; set; }
    }
}
