//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INDAABIN.DI.CONTRATOS.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraductorRUSP_Sector
    {
        public int Id_Registro { get; set; }
        public Nullable<double> CveSector { get; set; }
        public string Sector { get; set; }
        public Nullable<double> CveRAMO { get; set; }
        public string RAMO { get; set; }
    }
}
