//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INDAABIN.DI.CONTRATOS.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_DWH_CONTRATORIUF
    {
        public Nullable<int> IdRIUF { get; set; }
        public int FolioContratoArrto { get; set; }
        public string DescripcionTipoArrendamiento { get; set; }
        public string DescripcionTipoContrato { get; set; }
        public decimal AreaOcupadaM2 { get; set; }
        public decimal MontoPagoMensual { get; set; }
        public System.DateTime FechaInicioOcupacion { get; set; }
        public System.DateTime FechaFinOcupacion { get; set; }
        public string PropietarioInmueble { get; set; }
        public string Arrendatario { get; set; }
        public string Secuencial { get; set; }
        public Nullable<int> SMOI { get; set; }
    }
}
