//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SandBoxDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuestionarios
    {
        public int IdPregunta { get; set; }
        public decimal Orden { get; set; }
        public byte Fk_IdTema { get; set; }
        public int Fk_IdConcepto { get; set; }
        public int Fk_IdDataType { get; set; }
        public bool EsDeterminante { get; set; }
        public bool EdoInicial { get; set; }
        public string ReglaNegocio { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    }
}
